Repository camunda/camunda-platform-helm, pull requests merged in 2022-12, with the labels that each got.

#497 ci: enhance k8s/gke integration tests
  .github/workflows/test-integration.yaml
  Makefile
  charts/camunda-platform/test/integration/integration_suite.go
  charts/camunda-platform/test/integration/integration_test.go
  charts/camunda-platform/test/integration/openshift_test.go
  charts/camunda-platform/test/integration/setup.go
  go.mod
  go.sum
Labels: kind/bug, kind/enhancement, size/m

#505 chore(optimize): correct spring uri env var name
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
Labels: fix

#506 refactor: use external keycloak host directly
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/test/identity/deployment_test.go
  charts/camunda-platform/test/operate/deployment_test.go
  charts/camunda-platform/test/optimize/deployment_test.go
  charts/camunda-platform/test/tasklist/deployment_test.go
Labels: kind/enhancement, size/s

#509 Release Camunda Platform Helm Chart v8.1.3
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: release
