Repository camunda/camunda-platform-helm, pull requests merged in 2023-10, with the labels that each got.

#884 refactor: move to elasticsearch 8
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-integration-main.yaml
  charts/camunda-platform/.helmignore
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/operate/templates/configmap.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/configmap.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/openshift/openshift-tuned.yaml
  charts/camunda-platform/openshift/patch.sh
  charts/camunda-platform/openshift/values-patch.yaml
  charts/camunda-platform/openshift/values.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/curator-configmap.yaml
  charts/camunda-platform/templates/curator-cronjob.yaml
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-custom-values/values-custom.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/data-integration-elasticsearch-master-0.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/data-integration-elasticsearch-master-1.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/vars/common.env
  charts/camunda-platform/test/integration/scenarios/vars/dynamic.env
  charts/camunda-platform/test/integration/scenarios/vars/openshift.env
  charts/camunda-platform/test/integration/testsuites/base/files/variables-default.yaml
  charts/camunda-platform/test/integration/testsuites/base/files/variables-ingress-combined.yaml
  charts/camunda-platform/test/unit/curator_test.go
  charts/camunda-platform/test/unit/global_deployment_test.go
  charts/camunda-platform/test/unit/golden/curator-configmap.golden.yaml
  charts/camunda-platform/test/unit/operate/configmap_test.go
  charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/configmap_test.go
  charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-latest.yaml
Labels: size/l, test-persistent

#909 feat(identity): add multi-tenancy config
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/charts/identity/templates/configmap-env-vars.yaml
  charts/camunda-platform/charts/identity/templates/constraints.tpl
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/identity/templates/postgresql-secret.yaml
  charts/camunda-platform/test/unit/identity/configmap_test.go
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/secret_test.go
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/optimize/deployment_test.go
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s

#927 fix: use new disk usage configs for zeebe
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: size/xs, kind/fix

#929 follow-up: fix identity postgres multi-tendency auth
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/charts/identity/templates/postgresql-secret.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/secret_test.go
  charts/camunda-platform/values.yaml
Labels: kind/fix, test-persistent

#864 feat(security): read-only root filesystems for all containers
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/test/unit/connectors/deployment_test.go
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/deployment_test.go
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/test/unit/zeebe/statefulset_test.go
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/l, area/security

#912 chore: generate markdown from values file
  .github/workflows/chart-update-readme.yaml
  charts/camunda-platform/README.md
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, kind/docs

#942 Release Camunda Platform Helm Chart v8.1.17
  Makefile
  charts/camunda-platform/.helmignore
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
  charts/camunda-platform/test/golden/curator-configmap.golden.yaml
  charts/camunda-platform/test/golden/curator-cronjob.golden.yaml
  charts/camunda-platform/test/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/golden/service-monitor.golden.yaml
  charts/camunda-platform/test/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/identity/golden/ingress.golden.yaml
  charts/camunda-platform/test/identity/golden/operate-secret.golden.yaml
  charts/camunda-platform/test/identity/golden/service.golden.yaml
  charts/camunda-platform/test/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/identity/golden/tasklist-secret.golden.yaml
  charts/camunda-platform/test/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/operate/golden/service.golden.yaml
  charts/camunda-platform/test/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/optimize/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/optimize/golden/ingress.golden.yaml
  charts/camunda-platform/test/optimize/golden/service.golden.yaml
  charts/camunda-platform/test/optimize/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform/test/tasklist/golden/service.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-service.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/ingress.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/serviceaccount-annotations.golden.yaml
  charts/camunda-platform/test/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform/test/zeebe/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/zeebe/golden/service.golden.yaml
  charts/camunda-platform/test/zeebe/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: camunda-platform, chore, release

#943 Release Camunda Platform Helm Chart v8.2.16
  Makefile
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/service.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/golden/curator-configmap.golden.yaml
  charts/camunda-platform/test/unit/golden/curator-cronjob.golden.yaml
  charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/unit/golden/service-monitor.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/operate-secret.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/service.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/tasklist-secret.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/service.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/service.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-service.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/serviceaccount-annotations.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/service.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-latest.yaml
Labels: camunda-platform, chore, release

#945 Release Camunda Platform Helm Chart v8.3.0
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: camunda-platform, chore, release

#931 feat(console-sm): integrate with identity
  .vscode/settings.json
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/charts/identity/templates/console-secret.yaml
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/templates/console/deployment.yaml
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/m

#960 fix(operate,tasklist): readonly add zeebe cache path
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: size/s, kind/fix

#964 refactor: move operate to the parent chart
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/operate/.helmignore
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/operate/README.md
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/connectors/_helpers.tpl
  charts/camunda-platform/templates/ingress.yaml
  charts/camunda-platform/templates/operate/_helpers.tpl
  charts/camunda-platform/templates/operate/configmap.yaml
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/operate/ingress.yaml
  charts/camunda-platform/templates/operate/service.yaml
  charts/camunda-platform/templates/operate/serviceaccount.yaml
  charts/camunda-platform/templates/operate/tests/test-connection.yaml
  charts/camunda-platform/templates/web-modeler/_helpers.tpl
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml
  charts/camunda-platform/test/unit/global_deployment_test.go
  charts/camunda-platform/test/unit/operate/configmap_test.go
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/operate/goldenfiles_test.go
  charts/camunda-platform/test/unit/operate/ingress_test.go
  charts/camunda-platform/test/unit/operate/service_test.go
Labels: size/m, kind/refactor

#973 refactor: move optimize to the main chart
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/charts/optimize/.helmignore
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/optimize/README.md
  charts/camunda-platform/charts/optimize/templates/_helpers.tpl
  charts/camunda-platform/charts/optimize/templates/ingress.yaml
  charts/camunda-platform/charts/optimize/templates/serviceaccount.yaml
  charts/camunda-platform/charts/optimize/templates/tests/test-connection.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/ingress.yaml
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/optimize/_helpers.tpl
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/optimize/ingress.yaml
  charts/camunda-platform/templates/optimize/service.yaml
  charts/camunda-platform/templates/optimize/serviceaccount.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/unit/global_deployment_test.go
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/deployment_test.go
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/service.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/optimize/goldenfiles_test.go
  charts/camunda-platform/test/unit/optimize/ingress_test.go
  charts/camunda-platform/test/unit/optimize/service_test.go
Labels: size/s, kind/refactor

#962 fix: configure identity base url
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: size/s, kind/fix, version/8.3, test-persistent

#988 fix: use correct keycloak var for connectors
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/console/deployment.yaml
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/test/unit/connectors/deployment_test.go
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
Labels: size/s, kind/fix

#985 Adding OpenSSF to Github Actions workflows
  .github/workflows/ossf-scorecard.yml
Labels: size/s, area/security

#965 Adding linting to helm charts
  .github/config/yamllint.yaml
  .github/workflows/chart-validate.yaml
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/identity/templates/ingress.yaml
  charts/camunda-platform/charts/identity/templates/service.yaml
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/connectors/ingress.yaml
  charts/camunda-platform/templates/connectors/service.yaml
  charts/camunda-platform/templates/connectors/serviceaccount.yaml
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/operate/ingress.yaml
  charts/camunda-platform/templates/operate/service.yaml
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/optimize/ingress.yaml
  charts/camunda-platform/templates/optimize/service.yaml
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/tasklist/ingress.yaml
  charts/camunda-platform/templates/tasklist/service.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform/templates/web-modeler/ingress.yaml
  charts/camunda-platform/templates/web-modeler/service-restapi.yaml
  charts/camunda-platform/templates/web-modeler/service-webapp.yaml
  charts/camunda-platform/templates/web-modeler/service-websockets.yaml
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/templates/zeebe-gateway/ingress.yaml
  charts/camunda-platform/templates/zeebe-gateway/service.yaml
  charts/camunda-platform/templates/zeebe/statefulset.yaml
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/service.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/service.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/service.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-websockets.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/service.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: area/ci

#1003 Release Camunda Platform Helm Chart v8.3.1
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  scripts/verify-components-version.sh
Labels: camunda-platform, chore, release

#1013 fix: resource indent error
  .github/config/yamllint.yaml
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
Labels: kind/bug
