Repository camunda/camunda-platform-helm, pull requests merged in 2023-06, with the labels that each got.

#731 docs: includes note about adding environment variables using env option
  charts/camunda-platform/README.md
Labels: support, size/s, kind/docs

#737 feat: customize Identity firstUser creation
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/templates/NOTES.txt
  charts/camunda-platform/templates/tests/integration-test-secret.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s

#744 Release Camunda Platform Helm Chart v8.2.6
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release
