Repository camunda/camunda-platform-helm, pull requests merged in 2023-05, with the labels that each got.

#631 fix(connectors): adds correct handling of context path
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/ingress.yaml
  charts/camunda-platform/test/unit/connectors/deployment_test.go
Labels: kind/bug, size/s

#635 fix(follow-up): add contextPath to startup/readiness/liveness probes
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
Labels: size/xs, kind/fix

#640 ci: support web-modeler and connectors in the update image pipeline
  .github/workflows/chart-update-image-tag.yaml
  charts/camunda-platform/values.yaml
  scripts/update-values-file-image-tag.sh
Labels: kind/enhancement, size/s

#634 feat: zeebe gateway authentication
  .github/workflows/test-integration-kubernetes.yaml
  .github/workflows/test-integration-openshift.yaml
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/identity/templates/zeebe-secret.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/test/integration/scenarios/chart-upgrade/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
  charts/camunda-platform/test/integration/testsuites/base/job.yaml
  charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/m

#649 chore: tidy up keycloak values
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/values.yaml
Labels: size/xs

#651 Release Camunda Platform Helm Chart v8.2.3
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-cloud, release

#657 test: introduce retry within the integration tests
  .github/workflows/test-integration-kubernetes.yaml
  .github/workflows/test-integration-openshift.yaml
  charts/camunda-platform/test/integration/scenarios/lib/testsuite-deploy-taskfile.yaml
  charts/camunda-platform/test/integration/testsuites/base/job.yaml
  charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml
Labels: kind/enhancement, area/ci, size/s, area/test

#661 feat: values file level backporting per minor version
  .github/workflows/test-regression.yaml
  charts/camunda-platform/README.md
  charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-v8.0.yaml
  charts/camunda-platform/values/values-v8.1.yaml
Labels: kind/enhancement

#671 chore: Configure Renovate Bot to update apps and tools automatically
  .github/renovate.json5
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-v8.0.yaml
  charts/camunda-platform/values/values-v8.1.yaml
  renovate.json
Labels: kind/enhancement, size/m

#693 ci: setup renovate workflows
  .github/workflows/renovate-config-check.yaml
  .github/workflows/renovate-post-upgrade.yaml
  .github/workflows/test-integration-kubernetes.yaml
  .github/workflows/test-integration-openshift.yaml
Labels: chore, area/ci

#700 Release Camunda Platform Helm Chart v8.2.4
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#701 chore: use web-modeler version from docker instead of github-release
  .github/renovate.json5
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-v8.1.yaml
Labels: size/s, area/deps

#712 refactor: print zeebe env vars in debug mode only
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/zeebe/templates/configmap.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform/values.yaml
Labels: size/s, area/security

#713 ci: remove old mechanism to update image tags
  .github/workflows/chart-update-image-tag.yaml
  RELEASE.md
  charts/camunda-platform/values.yaml
  scripts/update-values-file-image-tag.sh
Labels: cleanup, area/ci

#715 fix: invalid redirect uri in the apps
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/values/values-v8.0.yaml
  charts/camunda-platform/values/values-v8.1.yaml
Labels: size/s, kind/fix

#717 Release Camunda Platform Helm Chart v8.2.5
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release, ad-hoc

#720 feat: add scheme to all probes
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s

#722 feat: support external url templating based on global ingress host
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/identity/templates/ingress.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/operate/templates/ingress.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/ingress.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/ingress.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/ingress.yaml
  charts/camunda-platform/templates/connectors/ingress.yaml
  charts/camunda-platform/templates/ingress.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/web-modeler/ingress.yaml
Labels: kind/enhancement, size/s
