Repository camunda/camunda-platform-helm, pull requests merged in 2023-12, with the labels that each got.

#1109 ci: make a template from integration test workflow
  .github/workflows/chart-validate.yaml
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-integration.yaml
  docs/gha-workflows.md
Labels: area/ci, size/xs

#1101 refactor: mount tasklist-configmap volume on a new path
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: kind/refactor, size/xs

#1107 ci: re-enable service monitor tests
  charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml
Labels: area/ci, area/test, size/xs

#1138 Release Camunda Platform Helm Chart v8.1.21
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#1141 Release Camunda Platform Helm Chart v8.2.19
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#1132 refactor: show error message for optimize requirements
  charts/camunda-platform/templates/camunda/constraints.tpl
  charts/camunda-platform/test/unit/camunda/global_deployment_test.go
Labels: kind/refactor, size/xs

#1145 refactor: mount tasklist-configmap volume on a new path [Backport to 8.1] (#1101)
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
Labels: kind/refactor

#1159 docs: rename example deployment name
  charts/camunda-platform/README.md
Labels: kind/docs, size/xs

#1160 refactor: fail if Multi-Tenancy requirements are not met
  charts/camunda-platform/charts/identity/templates/constraints.tpl
  charts/camunda-platform/templates/camunda/constraints.tpl
  charts/camunda-platform/test/unit/camunda/global_deployment_test.go
Labels: kind/refactor, size/xs

#1130 refactor: upgrade elasticsearch image from 8.8.2 to 8.9.2
  .github/renovate.json5
  charts/camunda-platform/values.yaml
  charts/camunda-platform/values/values-latest.yaml
Labels: kind/task, size/xs

#1153 chore: added GH app token in add-to-project workflow
  .github/workflows/add-to-project.yml
Labels: area/ci, kind/task, size/xs, area/security

#1169 chore: fix chart-update-readme.yaml
  .github/workflows/chart-update-readme.yaml
Labels: area/ci, kind/fix

#1172 refactor: remove deprecated tasklist graphql playground
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/refactor, size/xs

#1171 refactor: update helm chart version schema
  .chglog/CHANGELOG.tpl.md
  .github/workflows/chart-public-files.yaml
  .github/workflows/chart-release.yaml
  CONTRIBUTING.md
  Makefile
  RELEASE.md
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/README.md
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/convertValuesDoc.sh
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  docs/gha-workflows.md
  scripts/generate-version-matrix.sh
Labels: area/ci, size/s, kind/refactor
