Repository camunda/camunda-platform-helm, pull requests merged in 2023-09, with the labels that each got.

#844 chore: add visual comments in the values file
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/xs

#868 refactor: copy tls secret declaratively
  .github/config/external-secret.yaml
  .github/workflows/test-integration-main.yaml
Labels: kind/enhancement, area/ci, size/s

#877 ci: fix renovate es docker matching
  .github/renovate.json5
  charts/camunda-platform/values/values-latest.yaml
  charts/camunda-platform/values/values-v8.0.yaml
  charts/camunda-platform/values/values-v8.1.yaml
Labels: area/ci, size/s, kind/fix

#880 Release Camunda Platform Helm Chart v8.2.13
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#881 Release Camunda Platform Helm Chart v8.1.16
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#882 Release Camunda Platform Helm Chart v8.0.20
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore

#890 feat: adding Zeebe configuration for Multi-tenancy
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, version/8.3

#904 ci: run unit tests as groups
  .github/workflows/test-unit.yml
  Makefile
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/test/unit/zeebe/statefulset_test.go
Labels: area/ci, size/s

#907 feat(operate): propagate global flag to Operate...
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/test/unit/operate/deployment_test.go
Labels: size/xs

#896 fix: enable optimize upgrade process as initContainer
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
Labels: kind/enhancement, size/s, version/8.3

#906 chore(MT): add `CAMUNDA_TASKLIST_MULTITENANCY_ENABLED` env variable
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
Labels: kind/enhancement, size/xs

#869 fix: correct command value
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform/test/unit/connectors/deployment_test.go
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/optimize/deployment_test.go
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/test/unit/zeebe/statefulset_test.go
Labels: size/s, kind/fix

#914 ci: test chart upgrade by default in the ci pipeline
  .github/workflows/test-integration-main.yaml
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade.yaml
Labels: kind/enhancement, area/ci, size/s

#916 Release Camunda Platform Helm Chart v8.2.15
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#748 refactor: in web-modeler switch to spring env vars for db config
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/web-modeler/_helpers.tpl
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/values.yaml
Labels: version/8.2, version/8.3, breaking-change

#918 ci: use the latest released chart in the upgrade
  .github/workflows/test-integration-main.yaml
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-custom-values/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-default-values/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/lib/chart-upgrade.yaml
  charts/camunda-platform/test/integration/scenarios/vars/common.env
  charts/camunda-platform/test/integration/scenarios/vars/openshift.env
Labels: area/ci, size/xs
