Repository camunda/camunda-platform-helm, pull requests merged in 2023-01, with the labels that each got.

#512 fix: use keycloak 7.1.6 from camunda repo index
  Makefile
  charts/camunda-platform/charts/identity/Chart.yaml
Labels: size/s, kind/issue

#515 chore: setup go cache in the ci pipelines
  .github/workflows/chart-release.yaml
  .github/workflows/test-integration-openshift.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-unit.yml
Labels: kind/enhancement, ci, size/s

#513 Add default actuator endpoints - Tasklist
  .gitignore
  charts/camunda-platform/charts/tasklist/templates/configmap.yaml
  charts/camunda-platform/test/tasklist/golden/configmap.golden.yaml
Labels: size/s

#516 Release Camunda Platform Helm Chart v8.1.4
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: release

#520 fix(ci): use gh app to auth bot pr
  .github/workflows/chart-update-image-tag.yaml
Labels: fix, ci, size/s

#523 chore: unify go setup
  .github/workflows/chart-release.yaml
  .github/workflows/test-integration-openshift.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-unit.yml
  .tool-versions
Labels: ci, size/s, workflow

#522 docs: add details about c8 helm chart versioning
  .vscode/settings.json
  README.md
  charts/camunda-platform/README.md
Labels: kind/docs

#528 chore(ci): set concurrency=1 by cancel-in-progress
  .github/workflows/chart-release.yaml
  .github/workflows/chart-validate.yaml
  .github/workflows/test-integration-openshift.yaml
  .github/workflows/test-integration.yaml
Labels: ci, size/s

#526 Release Camunda Platform Helm Chart v8.1.5
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/web-modeler/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: release

#532 fix: set missing elasticsearch prefix env var
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
Labels: kind/bug, size/s

#534 Keycloak v19 initial support
  .github/workflows/test-integration-openshift.yaml
  .github/workflows/test-integration.yaml
  .tool-versions
  charts/camunda-platform/README.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/test/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/ingress_test.go
  charts/camunda-platform/test/integration/connection.go
  charts/camunda-platform/test/integration/integration_suite.go
  charts/camunda-platform/test/integration/integration_test.go
  charts/camunda-platform/test/integration/openshift_test.go
  charts/camunda-platform/test/integration/values-keycloak-v19.yaml
  charts/camunda-platform/values.yaml
  go.mod
  go.sum
Labels: kind/enhancement
