Repository camunda/camunda-platform-helm, pull requests merged in 2023-04, with the labels that each got.

#600 refactor: remove deprecated charts
  README.md
  index.yaml
Labels: kind/enhancement, size/s, kind/docs

#601 refactor: enable readinessProbe by default for all components
  charts/camunda-platform/README.md
  charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s, kind/refactor, version/8.2

#602 refactor: switch keycloak from v16 to v19
  .github/workflows/test-integration-kubernetes.yaml
  .github/workflows/test-integration-openshift.yaml
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/test/integration/scenarios/chart-upgrade/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-keycloak-v19/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-keycloak-v19/chart-identity-keycloak-v19.yaml
  charts/camunda-platform/test/unit/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/values.yaml
Labels: size/s, kind/refactor, version/8.2

#598 fix: add `CAMUNDA_TASKLIST_IDENTITY_REDIRECT_ROOT_URL` var
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: kind/bug, size/s

#603 refactor: enable connectors by default
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
  charts/camunda-platform/values.yaml
Labels: size/s, kind/refactor, version/8.2

#605 docs(deps): added connectors dependency onto diagram
  imgs/camunda-platform-8-self-managed-architecture-diagram-combined-ingress.png
Labels: kind/docs, version/8.2

#610 Release Camunda Platform Helm Chart v8.2.0
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/configmap-shared.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/secret-shared.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-websockets.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/serviceaccount.golden.yaml
  charts/camunda-platform/values.yaml
Labels: chore, release

#616 test: add web-modeler integration tests
  .github/workflows/test-integration-kubernetes.yaml
  .github/workflows/test-integration-openshift.yaml
  charts/camunda-platform/templates/web-modeler/service-webapp.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/Taskfile.yaml
  charts/camunda-platform/test/integration/scenarios/chart-with-web-modeler/values-web-modeler-enabled.yaml
  charts/camunda-platform/test/integration/scenarios/fixtures/values-integration-test.yaml
  charts/camunda-platform/test/integration/testsuites/base/files/vars.env
  charts/camunda-platform/test/integration/testsuites/base/job.yaml
  charts/camunda-platform/test/integration/testsuites/base/kustomization.yaml
  charts/camunda-platform/test/integration/testsuites/core/testsuites/core.yaml
  charts/camunda-platform/test/integration/testsuites/preflight/testsuites/preflight.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/service-webapp.golden.yaml
  charts/camunda-platform/values.yaml
Labels: area/ci, size/m, area/test

#625 fix: remove support for old built-in keycloak v16
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/test/unit/connectors/deployment_test.go
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/ingress_test.go
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/values.yaml
Labels: size/s

#629 fix: add contextPath to startup/readiness/liveness probes
  charts/camunda-platform/charts/identity/templates/deployment.yaml
  charts/camunda-platform/charts/operate/templates/deployment.yaml
  charts/camunda-platform/charts/optimize/templates/deployment.yaml
  charts/camunda-platform/charts/tasklist/templates/deployment.yaml
  charts/camunda-platform/charts/zeebe-gateway/templates/gateway-deployment.yaml
  charts/camunda-platform/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform/templates/_helpers.tpl
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/ingress.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/test/unit/connectors/deployment_test.go
  charts/camunda-platform/test/unit/identity/deployment_test.go
  charts/camunda-platform/test/unit/operate/deployment_test.go
  charts/camunda-platform/test/unit/optimize/deployment_test.go
  charts/camunda-platform/test/unit/tasklist/deployment_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform/test/unit/zeebe/statefulset_test.go
Labels: kind/bug, size/s
