Repository camunda/camunda-platform-helm, pull requests merged in 2024-07, with the labels that each got.

#2099 chore: add groups to renovate config
  .github/renovate.json5
Labels: workflow, size/xs

#2102 chore: update dep names
  .github/renovate.json5
  charts/camunda-platform-8.2/values-latest.yaml
  charts/camunda-platform-8.2/values.yaml
  charts/camunda-platform-8.3/values-latest.yaml
  charts/camunda-platform-8.3/values.yaml
  charts/camunda-platform-8.4/values-latest.yaml
  charts/camunda-platform-8.4/values.yaml
  charts/camunda-platform-alpha/values-latest.yaml
  charts/camunda-platform-alpha/values.yaml
  charts/camunda-platform-latest/values-latest.yaml
  charts/camunda-platform-latest/values.yaml
  charts/web-modeler-postgresql/values.yaml
Labels: area/workflow, size/xs

#2089 ci: adding workflow for pr conventions
  .github/workflows/pr-conventions.yaml
Labels: area/ci

#1816 feat(openshift): ci on-demand cluster openshift tests
  .github/actions/chart-test/action.yml
  .github/actions/workflow-vars/action.yml
  .github/config/rosa-on-demand/distribution-team/.gitignore
  .github/config/rosa-on-demand/distribution-team/external-cluster-secretstore.yaml
  .github/config/rosa-on-demand/distribution-team/external-secret.yaml
  .github/config/rosa-on-demand/distribution-team/kustomization.yaml
  .github/config/rosa-on-demand/distribution-team/secret.yaml.tpl
  .github/config/rosa-on-demand/external-dns/.gitignore
  .github/config/rosa-on-demand/external-dns/kustomization.yaml
  .github/config/rosa-on-demand/external-dns/secret.yaml.tpl
  .github/config/rosa-on-demand/kustomization.yaml
  .github/workflows/configs/test-integration-rosa-matrix.yaml
  .github/workflows/test-integration-rosa-cleanup.yml
  .github/workflows/test-integration-rosa.yaml
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-integration.yaml
Labels: area/ci, platform/openshift

#2117 fix(ci): failure alerts are not triggered on ROSA schedule integration
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-integration-rosa.yaml
Labels: kind/bug, area/ci

#2118 chore(ci): refactor rosa integration test workflow
  .github/actions/chart-test/action.yml
  .github/actions/gke-login/action.yml
  .github/actions/workflow-vars/action.yml
  .github/config/rosa-on-demand/test-integration-rosa-matrix.yaml
  .github/config/test-integration-matrix.yaml
  .github/workflows/configs/test-integration-rosa-matrix.yaml
  .github/workflows/test-integration-rosa-template.yaml
  .github/workflows/test-integration-rosa.yaml
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-integration.yaml
Labels: area/ci, size/s, kind/refactor, kind/medic

#2132 chore: fix gha expressions substitution in ci workflow
  .github/config/test-integration-matrix.yaml
  .github/workflows/test-integration-template.yaml
Labels: area/ci, size/xs, kind/fix, kind/medic

#2140 chore: update rosa actions
  .github/workflows/test-integration-rosa-template.yaml
Labels: dependencies

#2143 fix: added recreate strategy to all Operate deployments
  charts/camunda-platform-8.2/charts/operate/templates/deployment.yaml
  charts/camunda-platform-8.2/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-8.3/templates/operate/deployment.yaml
  charts/camunda-platform-8.3/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-8.4/templates/operate/deployment.yaml
  charts/camunda-platform-8.4/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/test/unit/operate/deployment_test.go
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-latest/templates/operate/deployment.yaml
  charts/camunda-platform-latest/test/unit/operate/deployment_test.go
  charts/camunda-platform-latest/test/unit/operate/golden/deployment.golden.yaml
Labels: priority/critical

#1761 refactor: make web-modeler restapi database password secret optional
  charts/camunda-platform-latest/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform-latest/test/unit/web-modeler/deployment_restapi_test.go
Labels: kind/fix, support, kind/medic
