Repository camunda/camunda-platform-helm, pull requests merged in 2024-06, with the labels that each got.

#1949 feat: support envFrom reference in all components
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/console/deployment.yaml
  charts/camunda-platform/templates/identity/deployment.yaml
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/templates/zeebe/statefulset.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s, kind/task

#1973 refactor: add support for seccomp profiles in all components
  charts/camunda-platform/README.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement

#1980 chore: move version matrix files to root dir
  .github/workflows/chart-public-files.yaml
  .github/workflows/chart-release.yaml
  charts/camunda-platform-8.4/README.md
  charts/camunda-platform-8.4/VERSION-MATRIX.md
  scripts/generate-version-matrix.sh
  version-matrix/README.md
  version-matrix/camunda-1.3/README.md
  version-matrix/camunda-8.0/README.md
  version-matrix/camunda-8.1/README.md
  version-matrix/camunda-8.2/README.md
  version-matrix/camunda-8.3/README.md
  version-matrix/camunda-8.4/README.md
  version-matrix/camunda-8.5/README.md
Labels: kind/enhancement, size/xs

#1782 feat: add console auth vars
  charts/camunda-platform-latest/README.md
  charts/camunda-platform-latest/templates/console/configmap.yaml
  charts/camunda-platform-latest/test/unit/console/configmap_test.go
  charts/camunda-platform-latest/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-latest/test/unit/console/types.go
  charts/camunda-platform-latest/values.yaml
Labels: kind/enhancement

#2006 Release Camunda Platform Helm Chart v10.1.1
  .github/workflows/chart-release-snapshot.yaml
  charts/camunda-platform-latest/Chart.yaml
  charts/camunda-platform-latest/RELEASE-NOTES.md
  charts/camunda-platform-latest/values-latest.yaml
  scripts/generate-version-matrix.sh
  version-matrix/README.md
  version-matrix/camunda-8.5/README.md
Labels: camunda-platform, chore, release

#2013 ci: automate release chores
  .chglog/CHANGELOG.tpl.md
  .github/config/chart-testing.yaml
  .github/config/release-please/.release-please-manifest.json
  .github/config/release-please/release-please-config.json
  .github/workflows/chart-release-chores.yml
  .github/workflows/chart-release-pr.yml
  .github/workflows/chart-release.yaml
  .github/workflows/renovate-post-upgrade.yaml
  .github/workflows/test-regression.yaml
  .github/workflows/test-unit-template.yml
  .tool-versions
  Makefile
  charts/camunda-platform-8.2/Chart.yaml
  charts/camunda-platform-8.2/charts/identity/Chart.yaml
  charts/camunda-platform-8.3/Chart.yaml
  charts/camunda-platform-8.3/charts/identity/Chart.yaml
  charts/camunda-platform-8.4/Chart.yaml
  charts/camunda-platform-8.4/charts/identity/Chart.yaml
  charts/camunda-platform-latest/Chart.yaml
  scripts/generate-release-notes.sh
  scripts/generate-version-matrix.sh
Labels: kind/enhancement, area/ci, area/cd

#1984 ci: mange integration tests clean-up via ttl
  .github/actions/workflow-vars/action.yml
  .github/workflows/dispatch-integration-backport.yaml
  .github/workflows/dispatch-integration.yaml
  .github/workflows/test-integration-cleanup-template.yaml
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-regression.yaml
  docs/gha-workflows.md
Labels: area/ci

#2016 chore: enable alpha tests
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-alpha.yaml
  .github/workflows/test-integration.yaml
  charts/camunda-platform-alpha/test/unit/camunda/global_deployment_test.go
Labels: area/ci, area/test

#1718 chore(tasklist): update Tasklist with monorepo configuration
  charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/configmap_test.go
  charts/camunda-platform-alpha/test/unit/tasklist/deployment_test.go
  charts/camunda-platform-alpha/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/deployment.golden.yaml
Labels: version/8.6

#1709 chore(tasklist): configure Tasklist's management port
  charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
  charts/camunda-platform-alpha/templates/service-monitor/tasklist-service-monitor.yaml
  charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/service.yaml
  charts/camunda-platform-alpha/test/unit/camunda/golden/tasklist-service-monitor.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/service.golden.yaml
  charts/camunda-platform-alpha/values.yaml
Labels: version/8.6

#1672 refactor: configure zeebe-gateway context path
  charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap.golden.yaml
Labels: version/8.6

#1660 refactor: configure Operate's management port
  charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
  charts/camunda-platform-alpha/templates/operate/configmap.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/operate/service.yaml
  charts/camunda-platform-alpha/templates/service-monitor/operate-service-monitor.yaml
  charts/camunda-platform-alpha/test/unit/camunda/golden/operate-service-monitor.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform-alpha/values.yaml
Labels: version/8.6

#1647 fix: use gatewayAddress property instead of brokerContactPoint
  charts/camunda-platform-alpha/templates/operate/configmap.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/test/unit/operate/configmap_test.go
  charts/camunda-platform-alpha/test/unit/operate/deployment_test.go
  charts/camunda-platform-alpha/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
Labels: version/8.6

#1995 feat: configure Webapps with REST v2 Api
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/serviceaccount.golden.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/values.yaml
Labels: kind/enhancement, version/8.6

#2032 chore: add a note about camunda helm github repo
  README.md
Labels: kind/docs, size/xs, area/ux

#2009 feat: support dnsPolicy and dnsConfig for all components
  charts/camunda-platform-alpha/templates/connectors/deployment.yaml
  charts/camunda-platform-alpha/templates/console/deployment.yaml
  charts/camunda-platform-alpha/templates/identity/deployment.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/optimize/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/test/unit/console/deployment_test.go
  charts/camunda-platform-alpha/test/unit/identity/deployment_test.go
  charts/camunda-platform-alpha/test/unit/operate/deployment_test.go
  charts/camunda-platform-alpha/test/unit/optimize/deployment_test.go
  charts/camunda-platform-alpha/test/unit/tasklist/deployment_test.go
  charts/camunda-platform-alpha/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform-alpha/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform-alpha/test/unit/web-modeler/deployment_websockets_test.go
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform-alpha/test/unit/zeebe/statefulset_test.go
  charts/camunda-platform-alpha/values.yaml
  charts/camunda-platform-latest/README.md
  charts/camunda-platform-latest/templates/connectors/deployment.yaml
  charts/camunda-platform-latest/templates/console/deployment.yaml
  charts/camunda-platform-latest/templates/identity/deployment.yaml
  charts/camunda-platform-latest/templates/operate/deployment.yaml
  charts/camunda-platform-latest/templates/optimize/deployment.yaml
  charts/camunda-platform-latest/templates/tasklist/deployment.yaml
  charts/camunda-platform-latest/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform-latest/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-latest/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform-latest/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
  charts/camunda-platform-latest/test/unit/connectors/deployment_test.go
  charts/camunda-platform-latest/test/unit/console/deployment_test.go
  charts/camunda-platform-latest/test/unit/identity/deployment_test.go
  charts/camunda-platform-latest/test/unit/operate/deployment_test.go
  charts/camunda-platform-latest/test/unit/optimize/deployment_test.go
  charts/camunda-platform-latest/test/unit/tasklist/deployment_test.go
  charts/camunda-platform-latest/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform-latest/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform-latest/test/unit/web-modeler/deployment_websockets_test.go
  charts/camunda-platform-latest/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform-latest/test/unit/zeebe/statefulset_test.go
  charts/camunda-platform-latest/values.yaml
Labels: kind/enhancement

#2041 chore: split testsuites per chart version
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-regression.yaml
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/variables-default.yaml
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/variables-ingress-combined.yaml
  charts/camunda-platform-8.2/test/integration/testsuites/vars/kustomization.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/variables-default.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/variables-ingress-combined.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/kustomization.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/variables-default.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/variables-ingress-combined.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/kustomization.yaml
  charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-alpha/test/integration/testsuites/vars/kustomization.yaml
  charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-latest/test/integration/testsuites/vars/kustomization.yaml
  test/integration/scenarios/lib/testsuite-deploy-taskfile.yaml
  test/integration/testsuites/base/job.yaml
  test/integration/testsuites/base/kustomization.yaml
  test/integration/testsuites/core/kustomization.yaml
  test/integration/testsuites/core/patches/job.yaml
  test/integration/testsuites/preflight/kustomization.yaml
Labels: area/ci, size/s, kind/refactor, area/test

#2044 chore: fix workflow inputs print
  .github/workflows/test-integration-template.yaml
Labels: size/xs, kind/fix

#2046 chore: use new tag name for snapshots
  .github/workflows/chart-release-snapshot.yaml
  docs/release.md
Labels: area/ci, kind/refactor, size/xs

#2048 chore: use console latest tag for alpha
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/serviceaccount.golden.yaml
  charts/camunda-platform-alpha/values.yaml
Labels: size/xs

#2049 chore: update zeebe gatway readiness probe tests
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-preflight.yaml
  charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-preflight.yaml
Labels: kind/refactor, area/test

#2053 feat: add camunda license config into all components
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/templates/camunda/_helpers.tpl
  charts/camunda-platform-alpha/templates/camunda/secret-camunda-license.yaml
  charts/camunda-platform-alpha/templates/connectors/deployment.yaml
  charts/camunda-platform-alpha/templates/console/deployment.yaml
  charts/camunda-platform-alpha/templates/identity/deployment.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/optimize/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/test/unit/camunda/secret_test.go
  charts/camunda-platform-alpha/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform-alpha/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform-alpha/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-alpha/values.yaml
Labels: kind/enhancement, size/s, version/8.6

#2060 chore: add workflow to check pr checks status
  .github/workflows/repo-pr-status.yaml
Labels: area/ci

#2069 refactor: remove the global image tag value and use it from the components
  .github/workflows/chart-release.yaml
  charts/camunda-platform-alpha/values-latest.yaml
  charts/camunda-platform-latest/README.md
  charts/camunda-platform-latest/test/unit/identity/golden/configmap.golden.yaml
  charts/camunda-platform-latest/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform-latest/test/unit/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-latest/test/unit/identity/golden/ingress.golden.yaml
  charts/camunda-platform-latest/test/unit/identity/golden/service.golden.yaml
  charts/camunda-platform-latest/test/unit/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform-latest/values-latest.yaml
  charts/camunda-platform-latest/values.yaml
Labels: kind/refactor, version/8.5, version/8.6
