Repository camunda/camunda-platform-helm, pull requests merged in 2024-05, with the labels that each got.

#1720 Release Camunda Platform Helm Chart v10.0.3
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
Labels: camunda-platform, chore, release

#1723 Release Camunda Platform Helm Chart v10.0.4
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
Labels: camunda-platform, chore, release

#1716 ci: enrich release notes and version matrix
  .github/workflows/chart-public-files.yaml
  Makefile
  charts/camunda-platform/VERSION-MATRIX.md
  scripts/generate-version-matrix.sh
Labels: area/ci, area/ux

#1717 fix: add constraints for when identity is disabled and keycloak is enabled
  charts/camunda-platform/templates/camunda/constraints.tpl
  charts/camunda-platform/test/unit/camunda/identitykeycloak_constraints_test.go
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform/test/unit/console/golden/serviceaccount.golden.yaml
Labels: kind/issue, kind/fix

#1743 fix: set zeebe exporters empty map when disabled
  charts/camunda-platform/templates/zeebe/configmap.yaml
Labels: size/xs, kind/fix

#1742 docs: enhance version matrix structure
  .github/workflows/chart-public-files.yaml
  .github/workflows/chart-release.yaml
  Makefile
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/values.yaml
  charts/camunda-platform/version-matrix/README.md
  charts/camunda-platform/version-matrix/camunda-1.3/README.md
  charts/camunda-platform/version-matrix/camunda-8.0/README.md
  charts/camunda-platform/version-matrix/camunda-8.1/README.md
  charts/camunda-platform/version-matrix/camunda-8.2/README.md
  charts/camunda-platform/version-matrix/camunda-8.3/README.md
  charts/camunda-platform/version-matrix/camunda-8.4/README.md
  charts/camunda-platform/version-matrix/camunda-8.5/README.md
  scripts/generate-release-notes.sh
  scripts/generate-version-matrix.sh
  scripts/templates/release-notes/RELEASE-NOTES-FOOTER.md.tpl
  scripts/templates/version-matrix/.gomplate.yaml
  scripts/templates/version-matrix/VERSION-MATRIX-INDEX.md.tpl
  scripts/templates/version-matrix/VERSION-MATRIX-RELEASE.md.tpl
Labels: size/s

#1719 chore: added links to sections and workflow inputs documentation
  .github/workflows/test-integration-template.yaml
  docs/gha-workflows.md
Labels: kind/docs

#1752 fix: handle type of es url correctly
  charts/camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl
Labels: kind/bug, size/xs

#1753 fix: use component service account
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/camunda/_helpers.tpl
  charts/camunda-platform/templates/connectors/_helpers.tpl
  charts/camunda-platform/templates/connectors/deployment.yaml
  charts/camunda-platform/templates/connectors/serviceaccount.yaml
  charts/camunda-platform/templates/console/_helpers.tpl
  charts/camunda-platform/templates/identity/_helpers.tpl
  charts/camunda-platform/templates/identity/deployment.yaml
  charts/camunda-platform/templates/identity/serviceaccount.yaml
  charts/camunda-platform/templates/operate/_helpers.tpl
  charts/camunda-platform/templates/operate/deployment.yaml
  charts/camunda-platform/templates/optimize/_helpers.tpl
  charts/camunda-platform/templates/optimize/deployment.yaml
  charts/camunda-platform/templates/tasklist/_helpers.tpl
  charts/camunda-platform/templates/tasklist/deployment.yaml
  charts/camunda-platform/templates/web-modeler/_helpers.tpl
  charts/camunda-platform/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform/templates/zeebe-gateway/_helpers.tpl
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/templates/zeebe/_helpers.tpl
  charts/camunda-platform/templates/zeebe/serviceaccount.yaml
  charts/camunda-platform/templates/zeebe/statefulset.yaml
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/enhancement, size/s, kind/fix

#1791 Release Camunda Platform Helm Chart v8.2.27
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
Labels: camunda-platform, chore, release

#1792 Release Camunda Platform Helm Chart v8.3.12
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
Labels: camunda-platform, chore, release

#1803 Release Camunda Platform Helm Chart v10.0.5
  .github/workflows/chart-release.yaml
  .tool-versions
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/version-matrix/README.md
  charts/camunda-platform/version-matrix/camunda-8.2/README.md
  charts/camunda-platform/version-matrix/camunda-8.3/README.md
  charts/camunda-platform/version-matrix/camunda-8.4/README.md
  charts/camunda-platform/version-matrix/camunda-8.5/README.md
  charts/web-modeler-postgresql/Chart.yaml
  charts/web-modeler-postgresql/RELEASE-NOTES.md
Labels: camunda-platform, chore, release

#1817 fix: remove empty string to get rid of warnings for zeebe and connectors
  charts/camunda-platform/values.yaml
Labels: kind/fix, support

#1833 fix: kind values.yaml file disable keycloak
  kind/camunda-platform-core-kind-values.yaml
Labels: kind/bug, kind/support

#1843 Release Camunda Platform Helm Chart v9.3.5
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
Labels: camunda-platform, chore, release

#1856 ci: use 0.0.0-ci-snapshot as a version for ci workflows
  .github/actions/workflow-vars/action.yml
Labels: area/ci, kind/refactor, size/xs

#1858 fix: update livenessProbe endpoint of zeebe
  charts/camunda-platform/values.yaml
Labels: fix, kind/support, support

#1864 fix: Disabling Elasticsearch and enabling OpenSearch causes incorrect syntax in zeebe configmap
  charts/camunda-platform/templates/zeebe/configmap.yaml
Labels: fix, kind/support, support

#1853 fix: backport identity changes
  charts/camunda-platform/charts/identity/templates/_helpers.tpl
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
Labels: kind/fix, kind/support

#1822 ci: delete namespace with a completed deployment only after 24 hours
  .github/workflows/test-integration-cleanup-template.yaml
Labels: area/ci, area/test

#1875 refactor: removing pull_request_target
  .github/workflows/chart-update-readme.yaml
  .github/workflows/chart-validate.yaml
  .github/workflows/test-integration.yaml
Labels: area/ci, kind/refactor

#1885 fix: Updating the readme workflow
  .github/workflows/chart-update-readme.yaml
Labels: area/ci, kind/fix
