Repository camunda/camunda-platform-helm, pull requests merged in 2024-04, with the labels that each got.

#1494 refactor: adding zeebe rest config for Tasklist
  charts/camunda-platform/README.md
  charts/camunda-platform/templates/camunda/constraints.tpl
  charts/camunda-platform/templates/operate/configmap.yaml
  charts/camunda-platform/templates/tasklist/configmap.yaml
  charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/refactor, size/xs

#1508 feat(follow-up): enable zeebe contextPath for management port
  charts/camunda-platform/templates/service-monitor/zeebe-gateway-service-monitor.yaml
  charts/camunda-platform/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform/test/integration/testsuites/base/files/variables-ingress-combined.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/deployment_test.go
Labels: kind/enhancement, size/xs, test-persistent

#1523 ci: delete github environment after the pipeline is done
  .github/workflows/test-integration-template.yaml
  .github/workflows/test-integration.yaml
Labels: kind/enhancement, area/ci, size/s

#1544 refactor(follow-up): ensure that 8.5 keys refactoring is backward compatible
  .github/workflows/test-integration-template.yaml
  charts/camunda-platform/templates/camunda/_helpers.tpl
  charts/camunda-platform/templates/camunda/constraints.tpl
  charts/camunda-platform/templates/connectors/_helpers.tpl
  charts/camunda-platform/templates/console/_helpers.tpl
  charts/camunda-platform/templates/identity/constraints.tpl
  charts/camunda-platform/templates/web-modeler/constraints.tpl
  charts/camunda-platform/templates/zeebe-gateway/constraints.tpl
  charts/camunda-platform/templates/zeebe/z_compatibility_helpers.tpl
Labels: test-persistent

#1553 chore: update images for unreleased 8.5
  charts/camunda-platform/README.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/service.golden.yaml
  charts/camunda-platform/test/unit/connectors/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/service.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/service.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/configmap-shared.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-restapi.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/deployment-websockets.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/secret-shared.golden.yaml
  charts/camunda-platform/test/unit/web-modeler/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-grpc-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-grpc.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-rest-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/ingress-rest.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/service.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/serviceaccount-annotations.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/service.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: chore, dependencies, size/xs

#1548 fix: updated GHA envs for our integration tests
  .github/workflows/test-integration-template.yaml
Labels: area/ci

#1569 Release Camunda Platform Helm Chart v8.1.27
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/charts/identity/Chart.yaml
  charts/camunda-platform/charts/operate/Chart.yaml
  charts/camunda-platform/charts/optimize/Chart.yaml
  charts/camunda-platform/charts/tasklist/Chart.yaml
  charts/camunda-platform/charts/zeebe-gateway/Chart.yaml
  charts/camunda-platform/charts/zeebe/Chart.yaml
  charts/camunda-platform/test/golden/curator-configmap.golden.yaml
  charts/camunda-platform/test/golden/curator-cronjob.golden.yaml
  charts/camunda-platform/test/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform/test/golden/service-monitor.golden.yaml
  charts/camunda-platform/test/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/identity/golden/ingress.golden.yaml
  charts/camunda-platform/test/identity/golden/operate-secret.golden.yaml
  charts/camunda-platform/test/identity/golden/service.golden.yaml
  charts/camunda-platform/test/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/identity/golden/tasklist-secret.golden.yaml
  charts/camunda-platform/test/operate/golden/configmap.golden.yaml
  charts/camunda-platform/test/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/operate/golden/ingress.golden.yaml
  charts/camunda-platform/test/operate/golden/service.golden.yaml
  charts/camunda-platform/test/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform/test/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform/test/tasklist/golden/service.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-deployment.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-service.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/gateway-serviceaccount.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/ingress.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/zeebe-gateway/golden/serviceaccount-annotations.golden.yaml
  charts/camunda-platform/test/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform/test/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform/test/zeebe/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform/test/zeebe/golden/service.golden.yaml
  charts/camunda-platform/test/zeebe/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform/values.yaml
Labels: release

#1592 Release Camunda Platform Helm Chart v10.0.1
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
Labels: camunda-platform, chore, release

#1599 Release Camunda Platform Helm Chart v10.0.2
  charts/camunda-platform/Chart.yaml
  charts/camunda-platform/RELEASE-NOTES.md
  charts/camunda-platform/VERSION-MATRIX.md
  charts/camunda-platform/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/zeebe/golden/statefulset.golden.yaml
Labels: camunda-platform, chore, release

#1638 chore: use helm package for install and upgrade
  charts/camunda-platform/test/integration/scenarios/chart-full-setup/Taskfile.yaml
Labels: area/ci

#1634 fix: mismatch errors during installation z_compatibility_helpers.tpl
  charts/camunda-platform/templates/zeebe/z_compatibility_helpers.tpl
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform/test/unit/console/golden/serviceaccount.golden.yaml
Labels: kind/issue

#1686 ci: release chart snapshot from main branch
  .github/workflows/chart-release-snapshot.yaml
  README.md
  charts/camunda-platform/README.md
  docs/readme.md
  docs/release.md
Labels: kind/enhancement, area/ci, size/s, area/test

#1700 fix: ensured 8.5 compatibility layer works with sub-charts
  charts/camunda-platform/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl
Labels: kind/bug, kind/support, support

#1701 fix: keycloak realm in console component is hardcoded
  charts/camunda-platform/templates/console/deployment.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/values.yaml
Labels: kind/fix

#1703 fix: uses issuerBackendUrl if present before trying to calculate a keycloak url
  charts/camunda-platform/templates/identity/_helpers.tpl
  charts/camunda-platform/templates/identity/configmap.yaml
  charts/camunda-platform/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform/test/unit/console/golden/serviceaccount.golden.yaml
  charts/camunda-platform/test/unit/identity/configmap_test.go
  charts/camunda-platform/test/unit/identity/types.go
Labels: kind/bug
