Repository camunda/camunda-platform-helm, pull requests merged in 2024-08, with the labels that each got.

#1773 feat: add volumeClaimTemplates label selector in zeebe statefulSet
  charts/camunda-platform-8.2/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform-8.2/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.2/values.yaml
  charts/camunda-platform-8.3/README.md
  charts/camunda-platform-8.3/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.3/values.yaml
  charts/camunda-platform-8.4/README.md
  charts/camunda-platform-8.4/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.4/values.yaml
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/values.yaml
  charts/camunda-platform-latest/README.md
  charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
  charts/camunda-platform-latest/values.yaml
Labels: kind/enhancement, size/s, cycle/alpha4

#2034 ci: adding chart verifier validation
  .github/workflows/chart-validate-template.yaml
Labels: area/ci

#1910 fix: set the network host and port to the zeebeGateway config
  charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/deployment.golden.yaml
Labels: kind/fix, test-persistent, cycle/alpha3

#2180 chore: fix alpha upgrade ci workflow
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-alpha.yaml
  .github/workflows/test-integration-template.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/ingress_test.go
  charts/camunda-platform-latest/test/unit/zeebe-gateway/ingress_test.go
  test/integration/scenarios/chart-full-setup/Taskfile.yaml
  test/integration/scenarios/vars/common.env
  test/integration/scenarios/vars/dynamic.env
Labels: area/ci, size/s

#2183 fix: use correct image object
  charts/camunda-platform-alpha/templates/operate/_helpers.tpl
  charts/camunda-platform-latest/templates/operate/_helpers.tpl
Labels: size/xs, kind/fix

#2144 feat: support migration initcontainer for operate
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-alpha/values.yaml
  charts/camunda-platform-latest/README.md
  charts/camunda-platform-latest/templates/operate/deployment.yaml
  charts/camunda-platform-latest/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-latest/values.yaml
Labels: kind/enhancement, size/s

#2170 fix: drop namespace from zeebe advertisedHost and initialContactPoints
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
  charts/camunda-platform-latest/test/unit/zeebe/golden/statefulset.golden.yaml
Labels: cycle/alpha4

#2168 fix: existingSecret for OpenSearch password can be used without defining password literal
  charts/camunda-platform-alpha/templates/camunda/constraints.tpl
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/optimize/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-latest/templates/camunda/_helpers.tpl
  charts/camunda-platform-latest/templates/camunda/constraints.tpl
  charts/camunda-platform-latest/templates/operate/deployment.yaml
  charts/camunda-platform-latest/templates/optimize/deployment.yaml
  charts/camunda-platform-latest/templates/tasklist/deployment.yaml
  charts/camunda-platform-latest/templates/zeebe/statefulset.yaml
Labels: cycle/alpha4

#2040 feat: configure camunda database to be used by v2 API
  charts/camunda-platform-alpha/templates/operate/configmap.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/configmap.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/configmap.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
  charts/camunda-platform-alpha/test/unit/zeebe/golden/configmap.golden.yaml
Labels: cycle/alpha4

#2228 chore: add steps to use helm chart gha workflow
  .github/workflows/examples/test-helm-chart.yaml
  README.md
  docs/gha-workflows.md
Labels: area/ci, kind/docs, area/ux

#2081 fix: enable secrets deprecation flag in alpha by default
  .github/config/external-secret.yaml
  .github/workflows/test-regression.yaml
  charts/camunda-platform-8.2/templates/tests/integration-test-secret.yaml
  charts/camunda-platform-8.2/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform-8.2/test/integration/scenarios/common/values-integration-test.yaml
  charts/camunda-platform-8.3/templates/tests/integration-test-secret.yaml
  charts/camunda-platform-8.3/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform-8.3/test/integration/scenarios/common/values-integration-test.yaml
  charts/camunda-platform-8.4/templates/tests/integration-test-secret.yaml
  charts/camunda-platform-8.4/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform-8.4/test/integration/scenarios/common/values-integration-test.yaml
  charts/camunda-platform-alpha/templates/camunda/constraints.tpl
  charts/camunda-platform-alpha/templates/tests/integration-test-secret.yaml
  charts/camunda-platform-alpha/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform-alpha/test/integration/scenarios/common/values-integration-test.yaml
  charts/camunda-platform-alpha/values.yaml
  charts/camunda-platform-latest/templates/tests/integration-test-secret.yaml
  charts/camunda-platform-latest/test/integration/scenarios/chart-full-setup/values-integration-test-ingress.yaml
  charts/camunda-platform-latest/test/integration/scenarios/common/values-integration-test.yaml
  test/integration/scenarios/lib/chart-upgrade-taskfile.yaml
  test/integration/testsuites/core/patches/job.yaml
Labels: lifecycle/deprecated, area/ci

#2233 ci: provide stable infrastructure via gha workflow
  .github/actions/test-type-vars/action.yml
  .github/actions/workflow-vars/action.yml
  .github/workflows/test-integration-template.yaml
  charts/camunda-platform-8.2/test/integration/scenarios/infra/values-infra-preemptible.yaml
  charts/camunda-platform-8.2/test/integration/scenarios/infra/values-infra-standard.yaml
  charts/camunda-platform-8.3/test/integration/scenarios/infra/values-infra-preemptible.yaml
  charts/camunda-platform-8.3/test/integration/scenarios/infra/values-infra-standard.yaml
  charts/camunda-platform-8.4/test/integration/scenarios/infra/values-infra-preemptible.yaml
  charts/camunda-platform-8.4/test/integration/scenarios/infra/values-infra-standard.yaml
  charts/camunda-platform-alpha/test/integration/scenarios/infra/values-infra-preemptible.yaml
  charts/camunda-platform-alpha/test/integration/scenarios/infra/values-infra-standard.yaml
  charts/camunda-platform-latest/test/integration/scenarios/infra/values-infra-preemptible.yaml
  charts/camunda-platform-latest/test/integration/scenarios/infra/values-infra-standard.yaml
  docs/gha-workflows.md
Labels: area/ci, size/s

#2234 fix: reload identity when its config changed
  charts/camunda-platform-alpha/templates/identity/deployment.yaml
  charts/camunda-platform-latest/templates/identity/deployment.yaml
Labels: kind/bug, size/xs

#2238 fix: correctly intend operate migration envs
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-latest/templates/operate/deployment.yaml
Labels: kind/bug, fix

#2237 chore: enhance auto-labeling in the repo
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  .github/config/issue-labeler.yaml
  .github/config/pr-labeler.yaml
  .github/workflows/chart-release.yaml
  .github/workflows/chart-validate.yaml
  .github/workflows/repo-issue-labeler.yaml
  .github/workflows/repo-pr-labeler.yaml
  Makefile
  scripts/set-prs-version-label.sh
Labels: kind/enhancement, area/ci, area/workflow

#2253 chore: fix venom version and syntax
  charts/camunda-platform-8.2/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-8.3/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-8.4/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-alpha/test/integration/testsuites/vars/files/testsuite-core.yaml
  charts/camunda-platform-latest/test/integration/testsuites/vars/files/testsuite-core.yaml
  test/integration/scenarios/chart-full-setup/Taskfile.yaml
  test/integration/testsuites/base/job.yaml
  test/integration/testsuites/base/kustomization.yaml
Labels: area/ci, area/test, size/xs

#2250 fix: add zeebe opensearch retention to app config file
  charts/camunda-platform-alpha/templates/zeebe/configmap.yaml
  charts/camunda-platform-latest/templates/zeebe/configmap.yaml
Labels: size/xs, test-persistent, component/zeebe

#2254 chore: unify chart test gha workflows
  .github/workflows/chart-validate.yaml
  .github/workflows/test-integration.yaml
  .github/workflows/test-unit.yml
  .github/workflows/test-version-alpha.yaml
  .github/workflows/test-version-latest.yaml
  .github/workflows/test-version-maintenance.yaml
Labels: area/ci, size/xs, tool/github-actions

#2212 feat: adding `adaptSecurityContext` option in values.yaml for OpenShift SCC
  charts/camunda-platform-alpha/README.md
  charts/camunda-platform-alpha/openshift/values.yaml
  charts/camunda-platform-alpha/templates/camunda/constraints.tpl
  charts/camunda-platform-alpha/templates/connectors/deployment.yaml
  charts/camunda-platform-alpha/templates/console/deployment.yaml
  charts/camunda-platform-alpha/templates/identity/deployment.yaml
  charts/camunda-platform-alpha/templates/operate/deployment.yaml
  charts/camunda-platform-alpha/templates/optimize/deployment.yaml
  charts/camunda-platform-alpha/templates/tasklist/deployment.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-restapi.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-alpha/templates/web-modeler/deployment-websockets.yaml
  charts/camunda-platform-alpha/templates/zeebe-gateway/deployment.yaml
  charts/camunda-platform-alpha/templates/zeebe/1/2/3/4/5/6/7/8/z_compatibility_helpers.tpl
  charts/camunda-platform-alpha/templates/zeebe/statefulset.yaml
  charts/camunda-platform-alpha/test/unit/camunda/golden/keycloak-statefulset.golden.yaml
  charts/camunda-platform-alpha/test/unit/connectors/deployment_test.go
  charts/camunda-platform-alpha/test/unit/console/deployment_test.go
  charts/camunda-platform-alpha/test/unit/identity/deployment_test.go
  charts/camunda-platform-alpha/test/unit/operate/deployment_test.go
  charts/camunda-platform-alpha/test/unit/optimize/deployment_test.go
  charts/camunda-platform-alpha/test/unit/tasklist/deployment_test.go
  charts/camunda-platform-alpha/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform-alpha/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform-alpha/test/unit/zeebe/statefulset_test.go
  charts/camunda-platform-alpha/values.yaml
Labels: size/m, platform/openshift, impact/high, component/zeebe, component/web-modeler, component/identity, component/operate, component/optimize, component/tasklist, component/connectors, component/console

#2269 feat: adding play env var to web-modeler
  charts/camunda-platform-alpha/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-alpha/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
  charts/camunda-platform-latest/templates/web-modeler/deployment-webapp.yaml
  charts/camunda-platform-latest/test/unit/web-modeler/golden/deployment-webapp.golden.yaml
Labels: component/web-modeler
