Repository camunda/camunda-platform-helm, pull requests merged in 2025-04, with the labels that each got.

#3271 fix: by default use 8.8 but without the symlink
  .github/workflows/test-integration-template.yaml
Labels: area/ci, tool/github-actions

#3233 chore: replace Web Modeler cluster authentication type OAUTH with BEARER_TOKEN
  charts/camunda-platform-8.7/templates/web-modeler/_helpers.tpl
  charts/camunda-platform-8.7/test/unit/web-modeler/configmap_restapi_test.go
  charts/camunda-platform-8.7/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
  charts/camunda-platform-8.7/values.yaml
  charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml
  charts/camunda-platform-8.8/test/unit/web-modeler/configmap_restapi_test.go
  charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
  charts/camunda-platform-8.8/values.schema.json
  charts/camunda-platform-8.8/values.yaml
Labels: version/8.7, version/8.8, component/web-modeler, version/alpha

#3278 fix: task 448 refactor unit test in 8.6/test/unit/connectors (clean version)
  charts/camunda-platform-8.6/test/unit/connectors/configmap_test.go
  charts/camunda-platform-8.6/test/unit/connectors/deployment_test.go
  charts/camunda-platform-8.6/test/unit/connectors/inbound-secret_test.go
  charts/camunda-platform-8.6/test/unit/connectors/service_test.go
Labels: version/8.6

#3284 fix: manual version bumps renovate couldnt do
  .github/config/release-please/.release-please-manifest.json
  charts/camunda-platform-8.7/Chart.yaml
  charts/camunda-platform-8.7/README.md
  charts/camunda-platform-8.7/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/connectors/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/connectors/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/connectors/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/connectors/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/console/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/identity/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/operate/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/optimize/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/optimize/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/optimize/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/optimize/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/tasklist/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/tasklist/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/tasklist/golden/ingress-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/tasklist/golden/ingress.golden.yaml
  charts/camunda-platform-8.7/test/unit/tasklist/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/web-modeler/configmap_restapi_test.go
  charts/camunda-platform-8.7/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/deployment.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/ingress-grpc-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/ingress-grpc.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/ingress-rest-all-enabled.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/ingress-rest.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/serviceaccount-annotations.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe-gateway/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap-multiregion-failBack.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap-multiregion-failOver.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/configmap.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/poddisruptionbudget.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/service.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/serviceaccount.golden.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.7/values-latest.yaml
  charts/camunda-platform-8.7/values.yaml
Labels: area/ci, version/8.7, tool/release-please, tool/github-actions

#3287 fix: bump core and connectors to 8.8.0-alpha3
  charts/camunda-platform-8.8/values.yaml
Labels: version/8.8

#3289 fix: refactored unit tests for identity and operate in 8.6
  charts/camunda-platform-8.6/test/unit/identity/configmap_test.go
  charts/camunda-platform-8.6/test/unit/identity/deployment_test.go
  charts/camunda-platform-8.6/test/unit/identity/secret_test.go
  charts/camunda-platform-8.6/test/unit/identity/service_test.go
  charts/camunda-platform-8.6/test/unit/operate/configmap_test.go
  charts/camunda-platform-8.6/test/unit/operate/deployment_test.go
  charts/camunda-platform-8.6/test/unit/operate/service_test.go
Labels: version/8.6

#3298 fix: replace alpha tag with 8.8 in renovate
  .github/renovate.json5
Labels: tool/renovatebot

#3288 fix: refactor unit tests in 8.6/test/unit/console to new style
  charts/camunda-platform-8.6/test/unit/console/deployment_test.go
  charts/camunda-platform-8.6/test/unit/console/service_test.go
Labels: version/8.6

#3300 fix: refactored optimize unit tests to the new style for 8.6
  charts/camunda-platform-8.6/test/unit/optimize/configmap_test.go
  charts/camunda-platform-8.6/test/unit/optimize/deployment_test.go
  charts/camunda-platform-8.6/test/unit/optimize/service_test.go
Labels: version/8.6

#3301 fix: backport 8.6 refactoring on test/unit/camunda to 8.5
  charts/camunda-platform-8.5/test/unit/camunda/configmap_test.go
  charts/camunda-platform-8.5/test/unit/camunda/constraints_test.go
  charts/camunda-platform-8.5/test/unit/camunda/global_deployment_test.go
  charts/camunda-platform-8.5/test/unit/camunda/identitykeycloak_constraints_test.go
  charts/camunda-platform-8.5/test/unit/camunda/ingress_test.go
  charts/camunda-platform-8.5/test/unit/camunda/secret_test.go
  charts/camunda-platform-8.5/test/unit/testhelpers/testhelpers.go
Labels: version/8.5

#3302 fix: task 448 backport and refactor Camunda unit test refactor from 8.6 to 8.4
  charts/camunda-platform-8.4/test/unit/camunda/configmap_test.go
  charts/camunda-platform-8.4/test/unit/camunda/global_deployment_test.go
  charts/camunda-platform-8.4/test/unit/camunda/ingress_test.go
  charts/camunda-platform-8.4/test/unit/camunda/secret_test.go
  charts/camunda-platform-8.4/test/unit/testhelpers/testhelpers.go
Labels: version/8.4

#3303 fix: refactor camunda unit tests on 8.3 to the new style
  charts/camunda-platform-8.3/test/unit/camunda/global_deployment_test.go
  charts/camunda-platform-8.3/test/unit/camunda/ingress_test.go
  charts/camunda-platform-8.3/test/unit/camunda/secret_test.go
  charts/camunda-platform-8.3/test/unit/testhelpers/testhelpers.go
Labels: version/8.3

#3321 fix: refactor unit tests in zeebe-gateway to new style on 8.6
  charts/camunda-platform-8.6/test/unit/zeebe-gateway/configmap_test.go
  charts/camunda-platform-8.6/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform-8.6/test/unit/zeebe-gateway/poddisruptionbudget_test.go
  charts/camunda-platform-8.6/test/unit/zeebe-gateway/service_test.go
  charts/camunda-platform-8.6/test/unit/zeebe/statefulset_test.go
Labels: version/8.6

#3319 fix: refactor unit tests in webmodeller of 8.6 to new style
  charts/camunda-platform-8.6/test/unit/web-modeler/configmap_restapi_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/configmap_shared_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/configmap_webapp_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/deployment_websockets_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/secret_restapi_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/secret_shared_test.go
  charts/camunda-platform-8.6/test/unit/web-modeler/service_test.go
Labels: version/8.6

#3308 refactor: update core configMap with retention parameters
  charts/camunda-platform-8.8/templates/core/configmap.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/configmap-authorizations.golden.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/configmap.golden.yaml
  charts/camunda-platform-8.8/values.schema.json
Labels: version/8.8, component/core

#3320 fix: refactor of zeebe unit tests in 8.6
  charts/camunda-platform-8.6/test/unit/zeebe/configmap_test.go
  charts/camunda-platform-8.6/test/unit/zeebe/poddisruptionbudget_test.go
  charts/camunda-platform-8.6/test/unit/zeebe/service_test.go
  charts/camunda-platform-8.6/test/unit/zeebe/statefulset_test.go
Labels: version/8.6

#3324 fix: port of new style to camunda unit tests in 8.7
  charts/camunda-platform-8.7/test/unit/camunda/configmap_test.go
  charts/camunda-platform-8.7/test/unit/camunda/constraints_test.go
  charts/camunda-platform-8.7/test/unit/camunda/global_deployment_test.go
  charts/camunda-platform-8.7/test/unit/camunda/identitykeycloak_constraints_test.go
  charts/camunda-platform-8.7/test/unit/camunda/ingress_test.go
  charts/camunda-platform-8.7/test/unit/camunda/secret_test.go
  charts/camunda-platform-8.7/test/unit/testhelpers/testhelpers.go
Labels: version/8.7

#3342 fix: refactored unit tests to new style in zeebe 8.5
  charts/camunda-platform-8.5/test/unit/zeebe/configmap_test.go
  charts/camunda-platform-8.5/test/unit/zeebe/poddisruptionbudget_test.go
  charts/camunda-platform-8.5/test/unit/zeebe/service_test.go
  charts/camunda-platform-8.5/test/unit/zeebe/statefulset_test.go
Labels: version/8.5

#3334 fix: add elasticsearch golden files
  .github/config/yamllint.yaml
  charts/camunda-platform-8.3/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.3/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
  charts/camunda-platform-8.4/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.4/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
  charts/camunda-platform-8.5/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.5/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
  charts/camunda-platform-8.6/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.6/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
  charts/camunda-platform-8.7/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.7/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
  charts/camunda-platform-8.8/test/unit/camunda/elasticsearch_statefulset_test.go
  charts/camunda-platform-8.8/test/unit/camunda/golden/elasticsearch-statefulset.golden.yaml
Labels: area/ci, area/test, version/8.3, version/8.4, version/8.5, version/8.6, version/8.7, version/8.8, tool/github-actions

#3335 fix: refactored unit tests to new style in console
  .github/workflows/test-chart-version-template.yaml
  .github/workflows/test-chart-version.yaml
  charts/camunda-platform-8.5/test/unit/console/deployment_test.go
  charts/camunda-platform-8.5/test/unit/console/service_test.go
Labels: area/ci, version/8.5, tool/github-actions

#3364 fix: grpc port of zeebe gateway for venom tests
  charts/camunda-platform-8.5/test/integration/testsuites/vars/files/variables-default.yaml
  charts/camunda-platform-8.6/test/integration/testsuites/vars/files/variables-default.yaml
  charts/camunda-platform-8.7/test/integration/testsuites/vars/files/variables-default.yaml
Labels: area/test, version/8.5, version/8.6, version/8.7

#3360 fix: refactored unit tests in 8.4 to new style in tasklist
  charts/camunda-platform-8.4/test/unit/tasklist/configmap_test.go
  charts/camunda-platform-8.4/test/unit/tasklist/deployment_test.go
  charts/camunda-platform-8.4/test/unit/tasklist/service_test.go
Labels: version/8.4

#3359 fix: refactored unit tests in 8.4 to new style in zeebe
  charts/camunda-platform-8.4/test/unit/zeebe/poddisruptionbudget_test.go
  charts/camunda-platform-8.4/test/unit/zeebe/service_test.go
  charts/camunda-platform-8.4/test/unit/zeebe/statefulset_test.go
Labels: version/8.4

#3358 fix: refactored unit tests in 8.4 to new style in zeebe-gateway
  charts/camunda-platform-8.4/test/unit/zeebe-gateway/deployment_test.go
  charts/camunda-platform-8.4/test/unit/zeebe-gateway/poddisruptionbudget_test.go
  charts/camunda-platform-8.4/test/unit/zeebe-gateway/service_test.go
Labels: version/8.4

#3357 fix: refactored unit tests in 8.4 to new style in web modeler
  charts/camunda-platform-8.4/test/unit/web-modeler/configmap_shared_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/deployment_restapi_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/deployment_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/deployment_webapp_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/deployment_websockets_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/secret_restapi_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/secret_shared_test.go
  charts/camunda-platform-8.4/test/unit/web-modeler/service_test.go
Labels: version/8.4

#3367 fix: refactor 8 8 unit test console
  charts/camunda-platform-8.8/README.md
  charts/camunda-platform-8.8/test/unit/connectors/golden/deployment.golden.yaml
  charts/camunda-platform-8.8/test/unit/console/deployment_test.go
  charts/camunda-platform-8.8/test/unit/console/service_test.go
  charts/camunda-platform-8.8/test/unit/core/golden/configmap-authorizations.golden.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/configmap-log4j2.golden.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/configmap.golden.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/statefulset.golden.yaml
  charts/camunda-platform-8.8/test/unit/optimize/golden/deployment.golden.yaml
  charts/camunda-platform-8.8/test/unit/testhelpers/testhelpers.go
  charts/camunda-platform-8.8/values.schema.json
  charts/camunda-platform-8.8/values.yaml
Labels: version/8.8

#2660 fix: changed name of zeebegateway in console configmap
  charts/camunda-platform-8.8/templates/NOTES.txt
  charts/camunda-platform-8.8/templates/camunda/_helpers.tpl
  charts/camunda-platform-8.8/test/unit/console/golden/configmap.golden.yaml
Labels: size/xs, version/8.8, component/console, version/alpha

#2321 fix: add apiVersion and kind to PersistentVolumeClaims
  charts/camunda-platform-8.2/charts/zeebe/templates/statefulset.yaml
  charts/camunda-platform-8.2/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.3/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.3/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.4/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.4/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.5/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.5/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.6/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.6/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.7/templates/zeebe/statefulset.yaml
  charts/camunda-platform-8.7/test/unit/zeebe/golden/statefulset.golden.yaml
  charts/camunda-platform-8.8/templates/core/statefulset.yaml
  charts/camunda-platform-8.8/test/unit/core/golden/statefulset.golden.yaml
  charts/web-modeler-postgresql/templates/primary/statefulset.yaml
  charts/web-modeler-postgresql/templates/read/statefulset.yaml
Labels: version/8.2, version/8.3, component/zeebe, version/8.4, version/8.5, version/8.6, version/8.7, version/8.8, component/core

#3353 fix: elasticsearch.extraConfig is a table
  charts/camunda-platform-8.7/values.yaml
  charts/camunda-platform-8.8/values.schema.json
  charts/camunda-platform-8.8/values.yaml
Labels: version/8.7, version/8.8

#3392 ci: fix workflow input name of camunda version
  .github/workflows/test-chart-version-template.yaml
  .github/workflows/test-chart-version.yaml
Labels: area/ci, size/xs, kind/medic, tool/github-actions

#3396 feat: add basic auth for web-modeler
  charts/camunda-platform-8.8/go.mod
  charts/camunda-platform-8.8/templates/web-modeler/_helpers.tpl
  charts/camunda-platform-8.8/templates/web-modeler/configmap-restapi.yaml
  charts/camunda-platform-8.8/test/unit/web-modeler/configmap_restapi_test.go
Labels: kind/enhancement, version/8.8, component/web-modeler

#3397 fix: skip elasticsearch.extraConfig
  charts/camunda-platform-8.7/README.md
  charts/camunda-platform-8.7/values.yaml
  charts/camunda-platform-8.8/README.md
  charts/camunda-platform-8.8/test/unit/web-modeler/golden/configmap-restapi.golden.yaml
  charts/camunda-platform-8.8/values.schema.json
  charts/camunda-platform-8.8/values.yaml
Labels: version/8.7, version/8.8

#3413 fix: scenario default type
  .github/workflows/test-integration-template.yaml
Labels: area/ci, tool/github-actions
